insert into posts (user_id, category_id, title, content, view_count, creation_date) values (1, 1, 'Nanny Mcig Bang)', ' pacificus', 1, '2/8/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (2, 3, 'My Bllentine', 'Vaneensis', 2, '4/17/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (3, 4, 'The Gilded Cage', 'Zosterops pallidus', 3, '6/26/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (4, 2, 'Here and Elsewhere', 'Vombatus ursinus', 4, '7/6/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (5, 2, 'The Secret  Fight Back', 'unavailable', 5, '6/1/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (6, 1, 'Poison', 'Antilocapra americana', 6, '9/1/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (7, 1, 'Presence, The', 'Scolopax minor', 7, '8/5/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (8, 3, 'Green Lantern', 'Chlamydosaurus kingii', 8, '10/4/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (9, 2, 'Hands Ripper', 'Alces alces', 9, '8/18/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (10, 1, 'Package, The', 'Gyps bengalensis', 10, '4/19/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (11, 2, '8 Daysi-iltaan)', 'Vanessa indica', 11, '4/8/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (12, 3, 'Baby Boy', 'Hystrix cristata', 12, '1/28/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (13, 4, 'Wave, The (Welle, Die)', 'Alopoptiacus', 13, '12/29/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (14, 1, 'Prize of ', 'Myrmecophaga tridactyla', 14, '9/24/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (15, 2, 'Permanent Record', 'Bos mutus', 15, '8/10/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (16, 2, 'Nô', 'Macropus robustus', 16, '3/13/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (17, 3, 'Archangel', 'Pseudocheirus peregrinus', 17, '4/9/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (18, 4, 'Poughk Tapes, The', 'Didelpana', 18, '12/25/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (19, 2, 'Shoot to Kill', 'Leprocaulinus vipera', 19, '7/10/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (20, 2, 'Living  olohuone)', ' tuberculifer', 20, '10/29/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (21, 2, 'The Land Unknown', 'Felis pardalis', 21, '6/24/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (22, 2, 'Your Highness', 'Sciurus vulgaris', 22, '9/18/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (23, 4, 'Afghan Luke', 'unavailable', 23, '12/9/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (24, 3, 'Auntie   Chicago)', 'unavailable', 24, '8/26/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (25, 4, 'Sarraounia', 'Lamprotornis superbus', 25, '2/15/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (26, 1, 'Colonel Chabert, Le', 'Cygnus buccinator', 26, '9/6/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (27, 1, 'Butterfly posas)', 'Nannopterum harrisi', 27, '1/7/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (28, 2, 'Poll  The (Poll)', 'Acrobamaeus', 28, '9/13/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (29, 3, '2046', 'Aonyx cinerea', 29, '8/14/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (30, 3, 'How to Rob a Bank', 'Certotrichas paena', 30, '1/2/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (31, 2, 'For the Moment', 'Delphinus delphis', 31, '3/14/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (32, 3, 'Independence Day ', 'Panthera leo persica', 32, '7/29/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (33, 3, 'Tiger apur, Der)', 'Phylurus milli', 33, '10/17/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (34, 4, 'In the Gods', 'Cyrto', 34, '2/19/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (35, 4, '12 Rounds 2: Reloaded', 'Phals lobatus', 35, '4/24/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (36, 1, 'Circle of Deceit', 'Eremstris', 36, '3/1/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (37, 2, 'Chapter Two', 'Centrasianus', 37, '12/8/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (38, 3, 'Notorious', 'Varanus salvator', 38, '10/21/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (39, 4, 'Galaxina', 'Gerbillus sp.', 39, '7/29/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (40, 4, 'Canyons, The', 'Felis concolor', 40, '11/4/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (41, 2, 'Duel at Diablo', 'Colobus guerza', 41, '1/10/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (42, 3, 'Day the  The', 'Uraeginthus bengalus', 42, '3/6/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (43, 4, 'Body Parts', 'Sarcophilus harrisii', 43, '1/15/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (44, 4, 'Hawk Is Dying, The', 'Gorilla gorilla', 44, '3/23/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (45, 4, 'Bruce Almighty', 'Ovis canadensis', 45, '8/7/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (46, 4, 'Fourth Angel, The', 'Cochlearius', 46, '8/20/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (47, 4, 'Lunch Break', 'Cebus apella', 47, '11/28/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (48, 4, 'Videocracy a apparire)', 'Phoca vitulina', 48, '11/30/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (49, 2, 'Of Human Bondage', 'Eolophus roseicapillus', 49, '1/6/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (50, 1, 'Simple Plan, A', 'Papio cynocephalus', 50, '10/22/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (51, 2, 'Paddington', 'Uraeginthus granatina', 51, '1/25/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (52, 3, 'Chained', 'Rhabdomys pumilio', 52, '9/18/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (53, 4, 'Cuckoo in a Dark ) ', 'Centrocercus ', 53, '7/2/2022');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (54, 1, 'Spanish Main, The', 'Cervus elaphus', 54, '3/16/2023');
insert into posts (user_id, category_id, title, content, view_count, creation_date) values (55, 1, 'Torch Song Trilogy', 'Panthera tigris', 55, '7/3/2022');
